# ===================================================================
# CONFIGURATION FOR THE GFS WEATHER DATA DOWNLOADER SCRIPT
# ===================================================================
# This file is used to manage all parameters without changing the code.
# Simply adjust the values below to fit your needs.

# --- General Project Settings ---
default:
  # The main folder where all downloaded data will be stored.
  base_folder: 'weather_data'
  # Sub-folder name for the data model being used.
  model_name: 'gfs_0.25'
  # Location or area code, used for creating sub-folders (e.g., 'afg' for Afghanistan).
  loc: 'afg'

# --- Technical Download Settings ---
download:
  # Number of parallel/concurrent downloads allowed.
  # Adjust according to your internet speed (higher is not always better).
  max_workers: 6
  # Timeout (in seconds) for a single file before it's considered failed.
  timeout: 90
  # Data size per chunk during download streaming (in bytes).
  chunk_size: 8192

# --- Logging Settings ---
logging:
  # File path for storing the process logs.
  file: 'weather_data/log/gfs_download.log'
  # Log detail level: DEBUG, INFO, WARNING, ERROR.
  level: 'INFO'

# --- Weather Forecast Parameters ---
forecast:
  # Maximum forecast duration (in hours) to be downloaded.
  max_hour: 24 # Example: 24 hours = 1-day forecast
  # Time interval between forecast files (in hours).
  step: 1 # Example: 1 means download every hour (f000, f001, f002, ...)

# --- Specific GFS API Configuration ---
gfs_api:
  # Base URL for the NOAA NOMADS GFS 0.25-degree data filter.
  base_url: 'https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25.pl'
  # Estimated delay (in hours) from the cycle time (00Z, 06Z, etc.) until the data is ready.
  availability_delay_hours: 4

  # --- Geographic Region (Bounding Box) ---
  region:
    # Top Latitude (Northern Boundary)
    toplat: 50
    # Left Longitude (Western Boundary)
    leftlon: 50
    # Right Longitude (Eastern Boundary)
    rightlon: 85
    # Bottom Latitude (Southern Boundary)
    bottomlat: 20

  # --- Desired Weather Variables ---
  variables:
    - APCP  # Accumulated Precipitation
    - TCDC  # Total Cloud Cover
    - RH    # Relative Humidity
    - TMP   # Temperature
    - DPT   # Dew Point Temperature
    - VIS   # Visibility
    - UGRD  # U-component of Wind (West-East)
    - VGRD  # V-component of Wind (South-North)

  # --- Desired Atmospheric Levels ---
  level:
    - 2_m_above_ground # For parameters at 2m height (TMP, RH, DPT)
    - surface          # For surface-level parameters (APCP, VIS)
    - 1000_mb          # 1000 mb pressure level
    - 850_mb           # 850 mb pressure level
    - 700_mb           # 700 mb pressure level
    - 500_mb           # 500 mb pressure level
